#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -z "$(head -n 1 $1)" ]; then
  echo "Aborting due to empty commit message"
  exit 1
fi
if ! head -1 "$1" | grep -qE "^(init|feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message is invalid." >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi
